### ISSUE TITLE
UCUS98632 1.00 support

### ISSUE THREAD

**Issue by stefan-girlich** [Kethen/RemasteredControls_GTpsp#1]
Thanks so much for creating this patch; this would make Gran Turismo on PPSSPP my perfect portable racing sim :)
I tried installing the plugin by moving the files (.ini and .prx) to a new folder `PSP/PLUGINS/gt_remastered`. However, the mapped inputs (e.g. `RightAn.Left`) don't seem to work.

1. I'm using PPSSPP on Android - could this be the issue?
1. I'm running UCUS98632 v1.0 (because of my advanced savegame) - Is this version definitely not working with your patch or has it just not been tested?
2. Is there a way to determine if a plugin has been loaded in PPSSPP, maybe via debug overlay? A log file `PSP/GTRemastered.log` has been created; see [GTRemastered.log](https://github.com/Kethen/RemasteredControls_GTpsp/files/13369710/GTRemastered.log)

Thanks again for your work. I'm a huge fan of sim racing and racing games and the only thing I missed about Gran Turismo on the PSP has been the lack of analog throttle and break inputs.

Update: A newer log shows that the game version seems to be the issue indeed:
```
disc id is UCUS98632
disc version is 1.00
game_base_addr: 0x8804028
unknown dics id UCUS98632 with version 1.00
cannot lookup function offsets with disc id and version, aborting
```

**Comment by Kethen** [comment]
Hi @stefan-girlich, is it possible for you to upgrade to UCUS98632 v2.00? Save games should be compatible since the disc id is the same. Please make a backup of your save and test that if you have access to v2.00

Alternatively if you absolutely can't use v2.00 instead, I'd need at least a ram dump starting from exactly 0x08804028 to 0x88000000, not sure if one can generate ram dumps on android ppsspp

**Comment by stefan-girlich** [comment]
Thanks for the quick answer, @Kethen . Controls now work as expected after copying the save game files (now using UCES01245 2.00)
Unrelated question: Loading a save state created while the plugin is active will crash PPSSPP for me; the PPSSPP Android app closes without an error message. This also occurs with a completely fresh save game and should therefore be unrelated to copying the save game files.
Is this a known issue? The [PPSSPP Plugins docs](https://www.ppsspp.org/docs/reference/plugins/#save-states) mention general compatibility, but recommend not using save states together with plugins. Let me know if you think this could be fixed; I can create a new GitHub issue with logs etc.
