### ISSUE TITLE
PPSSPP save state issues

### ISSUE THREAD

**Issue by Kethen** [Kethen/RemasteredControls_GTpsp#2]
@stefan-girlich Thanks for reporting that PPSSPP save state has issue loading! I've never used savestate on the game myself so I never noticed

Please check if this build fixes the issue on android as well, I'll make another release if it runs fine over there
https://github.com/Kethen/RemasteredControls_GTpsp/actions/runs/6893373667

Edit: or the latest on CI in general

**Comment by stefan-girlich** [comment]
Works like a charm on Android 13 using PPSSPP v1.16.6 and Gran Turismo UCES01245 2.00.
Thanks a lot for the quick fix; I really appreciate it :) 
We can resolve this issue. Feel free to mention me on GitHub if I can help with testing on Android.

**Comment by Kethen** [comment]
Thanks for verifying
