### ISSUE TITLE
Keybinds Mapping

### ISSUE THREAD

**Issue by FayeReagan** [Kethen/RemasteredControls_GTpsp#4]
Greetings, Thank you for making GT for PSP more awesome!

Is it possible to change the mapping for analog throttle to right stick up and camera rotation to right stick left and right through "GTRemastered_camera_controls.txt" settings?

**Comment by Kethen** [comment]
Possible but not quite feasible

For players who enjoy drifting it makes sense to reserve two PSP axes for throttle and brake, which occupies both x(left right) and y(up down) axes of the right stick

That leaves the y axis on the left stick for the optional bumper/cockpit  camera control

With this setup players should be able to map all these axes already through PPSSPP settings, keeping things simple

**Comment by FayeReagan** [comment]
I get it now, I'll close this issue now

Thank you for still maintaining this plugin

**Comment by Eloren1** [comment]
How can I use camera controls? Up and down on the left stick do not work. I tried binding in ppsspp as well, it did not work either
